# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20d1974906e1be8919be8d8aa8e8b73e5869ad1e3c6d34c1de5a7bca7b7f941611b5cf79d9ab8d54f55193ed9eedad566be7684f3556dbfd9faf3a0c8fc9b6a3

test:
  secret_key_base: d00223a57336c553a6d81a579d02a1892d816bea87f7662580c6c9a0c961f3dca23b8003748943a49c6f4b6fcea35aec169ef34d8283362a24b73c07402f3ac5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
